### ISSUE TITLE
Автоматическое имя для файла

### ISSUE THREAD

**Issue by oukibt** [SuperZombi/HDrezka-Helper#13]
Здравствуйте. Возможно ли как-нибудь устанавливать имя для файла, который будет скачиваться при зажатом ALT?
Проблема в том, что они именуются пятизначным хэшем. После скачивания легко запутаться в номерах серий

**Comment by SuperZombi** [comment]
На жаль, при завантаженні файлів з інших ресурсів не можна встановити власне ім'я файлу. Як варіант можна зробити завантаження через blob (всередині сторінки), а не через API браузера.

**Comment by SuperZombi** [comment]
Зробив. Завантажте версію 4.0 з релізів, та увімкніть у налаштуваннях плагіна <code>Downloader 2.0</code>, а також можете вказати за яким шаблоном ви хотіли б завантажувати файли.
