### ISSUE TITLE
Максимальна якість тільки 480р

### ISSUE THREAD

**Issue by vladislaw438** [SuperZombi/HDrezka-Helper#16]
Зараз доступна максимальна якість тільки 480р, не розумію, зо сталося, декілька днів тому все працювало. А так дякую, скріпт топ, дуже рятує коли нема світла довго)

**Comment by SuperZombi** [comment]
Схоже резка чомусь не дає напряму доступ до 720p mp4 файлу (а скрипт зламався, бо завершив роботу через неочікувану помилку).
Вже [пофіксив](https://github.com/SuperZombi/HDrezka-Helper/releases), тепер він не падає, але 720 якості тепер на жаль немає (((
