### ISSUE TITLE
Шаблон имени фала не совсем удобен

### ISSUE THREAD

**Issue by oleghorest89982** [SuperZombi/HDrezka-Helper#19]
На данный момент шаблон имени фала не совсем удобен, особенно, учитывая тот момент, что некоторые используют сторонние менеджеры загрузок. Идеальным является реализация загрузки в приложении HDRezka Client, где название, а также, если это сериал, сезон и серия, берутся непосредственно с самой html страницы и записываются перед сгенерированным названием из букв и цифр для файла через нижнее подчеркивание.

**Comment by SuperZombi** [comment]
Вы можете изменить шаблон так как вам удобно в настройках.
![image](https://user-images.githubusercontent.com/75096786/218304781-830e5bbf-de95-4c1a-aaee-42cf2781fffc.png)

**Comment by oleghorest8996** [comment]
> Вы можете изменить шаблон так как вам удобно в настройках. ![image](https://user-images.githubusercontent.com/75096786/218304781-830e5bbf-de95-4c1a-aaee-42cf2781fffc.png)

Ну так этот шаблон актуален только для загрузки внутри страницы, которая, кстати, лично у меня работает ужасно, а не для стандартного браузерного менеджера загрузок или какого-то постороннего пользовательского. Downloader 2.0 с загрузкой внутри страницы не имеет даже тех элементарных функций, которые имеет встроенный браузерный менеджер. Поэтому, лично для меня, это ваще не вариант. Если бы данный шаблон работал с обычной, стандартной загрузкой, вопросов б не было. А так, лучше уж самому каждый раз прописывать имя, чем пользоваться загрузкой в внутри страницы. А прописывать, копировать каждый раз название, особенно если это сериал, мягко говоря, не очень удобно.

**Comment by SuperZombi** [comment]
К сожалению, при загрузке через стандартный браузерный менеджер, если файл находиться на отличающемся от текущего домена адресе, то задавать кастомное имя файла невозможно.

**Comment by oleghorest8996** [comment]
> К сожалению, при загрузке через стандартный браузерный менеджер, если файл находиться на отличающемся от текущего домена адресе, то задать кастомное имя файла невозможно.

А как тогда это реализовали разработчики HDRezka Client?

**Comment by SuperZombi** [comment]
хз що це. Я думаю вони юзали НЕ JS
