### ISSUE TITLE
Вказати дзеркало сайту самому

### ISSUE THREAD

**Issue by bohdangnatiuk** [SuperZombi/HDrezka-Helper#23]
В світлі останніх подій з блокуванням, я гадаю, було б добре мати можливість самому вказувати дзеркала сайту, на яких працюватиме розширення. Бо зараз доступний тільки вичерпний перелік дзеркал, а можливість самому вказати дзеркало — відсутня.

**Comment by bohdangnatiuk** [comment]
Бачу ви позначили тему як потрібна допомога. Як на мене, це не повинно викликати великих труднощів в реалізації. Можна зробити легким і сами логічним способом, це безпосередньо реалізувати через налаштування розширення в браузері, як наприклад, це зроблено в розширенні Modern scrollbar https://github.com/luandersonn/Modern-scrollbar Перший скрін. Єдине, може виникнути проблема з тим, що у вашому розширенні вже є кілька сайтів rezka внесених туди за замовчуванням, не знаю чи можна в такому випадку зробити, щоб користувач міг вносити туди зміни. Ще є розширення History Blacklist https://github.com/smrq/chrome-history-blacklist Другий скрін. В ньому складніша реалізація, сайти добавляються вже безпосередньо в налаштуваннях самого розширення. Ці обидва розширення з відкритим кодом, тому можна глянути, як там все реалізовано. Надіюсь, це якось допоможе і пришвидшить реалізацію, бо якщо дійсно почнуть блокувати і таки прийдеться використовувати та простити в рєзкі дзеркала, то вже розширення тоді стане не придатним.
![202311112137](https://github.com/SuperZombi/HDrezka-Helper/assets/150519585/9729363d-8799-4336-a19c-5208fb3427b8)
![unnamed](https://github.com/SuperZombi/HDrezka-Helper/assets/150519585/9b7ac876-ab5d-4733-8f01-204b14c9c6dc)

**Comment by SuperZombi** [comment]
Я бачу тільки один варіант:
Зробити в налаштуваннях розширення менюшку з додаванням сайтів.
А в маніфесті вказати background servise, який буде звірятися з масивом посилань з налаштувань.
Мінусі: при відкритті нової вкладки/сайту, розширення буде постійно запускати скрипт та перевіряти url.

**Comment by bohdangnatiuk** [comment]
> Я бачу тільки один варіант: Зробити в налаштуваннях розширення менюшку з додаванням сайтів. А в маніфесті вказати background servise, який буде звірятися з масивом посилань з налаштувань. Мінусі: при відкритті нової вкладки/сайту, розширення буде постійно запускати скрипт та перевіряти url.
> 
> Розширення, які ви привели в приклад працюють на всіх сайтах за замовчуванням. В нашому випадку таке робити буде не дуже добре.

Було б добре, якби користувач через менюшку, добавляв дзеркала безпосередньо в сам manifest.json. Але це певно не можливо. Що стосується Modern scrollbar, так, воно працює на всіх сайтах за замовчуванням, а вже безпосередньо сам користувач може вибрати режим тільки на певних сайтах і задати список сайтів. Я просто думав, що розробник може сам вказати режим за замовчуванням тільки на певних сайтах і задати список сайтів, який потім користувач зміг би доповнити. Але прочитавши бігло документацію, зрозумів, що то так не працює. Тільки через matches, який не змінний, що й ви використовуєте. А от History Blacklist, так, він формально працює на всіх сайтах як розширення, але виконує тільки свої функції з очищення історії, тільки на тих сайтах, які вкаже користувач. Тому я подумав, що хай собі розширення й працює на кожному сайті, але виводить кнопку завантаження тільки на тих сайтах, які вкаже користувач, ну й плюс задати вже шаблоні сайти розробником, на яких кнопка б виводилась.

Тим не менш, це просто приклади, які мені спали на думку. Якщо у вас є інше рішення через background servise, то це чудово. Реалізовуйте як знаєте, головне щоб працювало, ну й щоб ресурсів багато не споживало 😄

**Comment by DemiaKo** [comment]
я от додав дзеркало в manifest, і в налаштуваннях розширення пише, що воно має доступ до https://hdrezka720nnt.org (моє власне дзеркало), але кнопка скачки ніяк не появляється
 
Дзеркало я отримав від підтримки rezka

**Comment by SuperZombi** [comment]
> я от додав дзеркало в manifest, і в налаштуваннях розширення пише, що воно має доступ до сайту, але кнопка скачки ніяк не появляється

Там треба в двох місцях вказувати
```json
"web_accessible_resources": [
        {
        "resources": [ "myscript.js" ],
        "matches": [ ... , "https://вашсайт/*" ]
    }
],
"content_scripts": [{
    "matches": [ ... , "https://вашсайт/*" ],
    "js": ["script.js"],
},
```

**Comment by DemiaKo** [comment]
дякую, бо я був написав у 3 місцях (у третьому matches). Стер і все працює

**Comment by SuperZombi** [comment]
Сім'я. У мене гарна новина. Зробив версію `5.0`. В якій тепер можна додавати будь які дзеркала.
Тепер чекаємо поки гугл заапрувить дозвіл до всіх сайтів (може не дозволити).
І тоді буде свято!

**Comment by SuperZombi** [comment]
![IMG_20240820_223006](https://github.com/user-attachments/assets/c2808962-7317-4736-9504-b4762be26f10)
