### ISSUE TITLE
Завантажується текстовий файл з розширенням .m3u8

### ISSUE THREAD

**Issue by lawko** [SuperZombi/HDrezka-Helper#25]
Доброго дня. Використовую VPN від Cloudflare (1.1.1.1), працювало все добре, але сьогодні завантажуєтсья будь-яка серія за 1 секунду і результатом завантаження є текстовий файл з розширенням .mp4 наступного складу й таких рядків біля тисячі:
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:6.000,
./butze.mp4:hls:seg-1-v1-a1.ts
#EXTINF:6.000,
./butze.mp4:hls:seg-2-v1-a1.ts
Шо це може бути?)

**Comment by SuperZombi** [comment]
Fixed in `4.3.0`

**Comment by SuperZombi** [comment]
Не забувайте підтримувати розробника на donatello❤️ за такі швидкі фікси
