### ISSUE TITLE
Возможность указывать сайт

### ISSUE THREAD

**Issue by Cron5** [SuperZombi/HDrezka-Helper#27]
В настоящее время HDrezka прыгает по зеркалам из-за блокировок. Зеркала меняются раз в несколько дней. Прописанные в расширение зеркала не работают. По этой причине не появляется кнопка загрузки видео внизу под плеером.
Предложение - добавить в настройки расширения поле для ввода желаемого зеркала, с которым оно будет работать, либо пусть расширение работает на всех сайтах, если возможно.

**Comment by SuperZombi** [comment]
Dublicate #23

**Comment by SuperZombi** [comment]
Доступно в оновленні 5.0!
