### ISSUE TITLE
Eror resolution

### ISSUE THREAD

**Issue by Bladbk** [SuperZombi/HDrezka-Helper#28]
![2024-02-12_02-23-51](https://github.com/SuperZombi/HDrezka-Helper/assets/123633070/e25acf85-5606-4d9c-a80e-7510fe97fdec)

**Comment by Bladbk** [comment]
Привіт, помилка виникла в браузері chrome, пробував Яндекс, проблема не вирішилася. У чому суть проблеми: при натисканні на кнопку Завантаження немає потрібної якості, є всього 2 або 3 рядки. Спробував перезавантажити та перевстановити дозвіл, не допомагає . Зараз ноут перезавантажу.

**Comment by Bladbk** [comment]
Перезавантаження не допомогло. Сподіваюся що ця проблема вирішиться.

**Comment by SuperZombi** [comment]
VPN

**Comment by Bladbk** [comment]
Кілька разів змінив сервер у shadowrocet, допомогло не відразу, були проблеми у провайдера, зараз все працює, спасибі❤️.
