### ISSUE TITLE
Більше не відображається розмір файлу, як це було раніше

### ISSUE THREAD

**Issue by bohdangnatiuk** [SuperZombi/HDrezka-Helper#29]
В останній версії розширення, чомусь більше не відображається розмір файлу, як це було раніше. А це було досить корисно. Не знаю, можливо, це взагалі не проблема розширення, а проблема пов'язана з самим сервісом, що використовується для завантаження чи проблема взагалі зі сторони HDrezka через якісь їх нові обмеження 🤷‍♂️ Гадаю, варто звернути на це увагу і якщо є така можливість — виправте, будь ласка. Буду вельми вдячний.

![001](https://github.com/SuperZombi/HDrezka-Helper/assets/150519585/16c2c397-2418-4d41-8831-860da3fa552a)

**Comment by bohdangnatiuk** [comment]
> Я це зробив для того, щоб посилання взагалі відображалось, бо hdrezka не хоче давати розмір файлу. Спробуйте використовувати VPN.

Зрозуміло, спасибі за відповідь!

**Comment by SuperZombi** [comment]
Пофіксив у версії `4.3.2`. Тепер працює без VPN. Сподіваюсь ви підтримаєте автора за такий оперативний фікс. 🙃
