### ISSUE TITLE
Не работает Импорт\Экспорт Закладок

### ISSUE THREAD

**Issue by DeerFee** [SuperZombi/HDrezka-Helper#33]
Не работает функции закладок hdrezka.ag (другие домены просто не рабочие)
Нет значка который есть на скриншотах, и интерфейс расширения такой же как на странице сериала 
![image](https://github.com/user-attachments/assets/a7800f6b-afb0-4977-b73c-df89b63f571d)
Расширение последней версии из магазина хром (5.0.0)
Браузер Opera GX LVL6 (core: 112.0.5197.74) (Версия Chromium: 126.0.6478.226)
И проверял на Хроме 127.0.6533.122

**Comment by SuperZombi** [comment]
Я его убрал по причине что его никто не использует

**Comment by SuperZombi** [comment]
Если вам нужен експорт закладок. Он остался в юзер скрипте.

**Comment by DeerFee** [comment]
> Если вам нужен експорт закладок. Он остался в юзер скрипте.

Извиняюсь за вопрос к неактуальной версии скрипта, но - 
Есть ли у него какие то ограничения на одну вкладку?
Всего 9 вкладок, первая (7 тайтлов) и вторая (27 тайтлов) вкладки, экспортировались почти моментально, третья вкладка было на 5 страниц (176 тайтлов), дальше просто висит в игноре

Увидел ваш ответ и пошел тестить почти сразу
первую попытку провисело 5 минут и я выключил, второй раз уже 25 минут держу, все так же висит

**Comment by SuperZombi** [comment]
> Извиняюсь за вопрос к неактуальной версии скрипта, но - Есть ли у него какие то ограничения на одну вкладку? 

Он ходит по вкладкам и сохраняет данные в памяти. А потом дампит в json. По идее должен нормально ходить. Возможно у вас просто слабый пк и мало ОЗУ?
Попробуйте еще установить старую версию нативного расширения (для хрома вручную версией 4)

**Comment by DeerFee** [comment]
> Возможно у вас просто слабый пк и мало ОЗУ?

Есть такое, 8 гигов

> Попробуйте еще установить старую версию нативного расширения (для хрома вручную версией 4)

Пробовал через 4.1 и 4.0, все так же, 1 и 2 почти моментально, 3 висит уже 15 минут 

**В любом случае, спасибо за помощь!**
