### ISSUE TITLE
Предзагрузка видео в несколько потоков

### ISSUE THREAD

**Issue by SystemHunterD** [SuperZombi/HDrezka-Helper#34]
Некоторые фильмы и сериалы грузятся намного медленнее других, в зависимости из какой страны (или с каким впн) их смотреть.
Стандартная предзагрузка резки во время паузы загружает только отрезок размером 3-5мин и иногда смотреть сериал просто невыносимо.
Было бы кайфово если бы предзагрузка могла работать в несколько потоков (как торрент) и позволяла бы предзагрузить все видео целиком.

**Comment by SuperZombi** [comment]
Excuse me, I don't understand "кацапську".
Write to hdrezka's support. If you need to pre-load a movie, just download it. I don't see this as a problem.
