### ISSUE TITLE
Расширение под Firefox

### ISSUE THREAD

**Issue by RomanBiluy** [SuperZombi/HDrezka-Helper#8]
Не могли бы вы разработать такое же расширение под Firefox?

**Comment by SuperZombi** [comment]
Возможно в будущем

**Comment by SuperZombi** [comment]
@RomanBiluy, попробуйте использовать с Tampermonkey

**Comment by SuperZombi** [comment]
Добавил поддержку Firefox. Отправил на проверку в магазин мозилы.
Чисто в теории будет работать даже на файрефоксе на телефоне.
Осталось только молиться, чтобы пропустили расширение в магазин

**Comment by SuperZombi** [comment]
![IMG_20240828_201930](https://github.com/user-attachments/assets/49b0c800-42c0-459b-b49f-00fceac4cd97)
